// Type stub for dotnet.boot.js generated by build.mjs.
export interface BootAsset { name: string; behavior: string; }
export interface BootConfig { mainAssemblyName: string; globalizationMode: string; assets: BootAsset[]; }
declare const bootConfig: BootConfig;
export default bootConfig;
